//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scch.Logging.UdpTraceListener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scch.Logging.UdpTraceListener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The footer of the message..
        /// </summary>
        internal static string UdpTraceListenerFooterDescription {
            get {
                return ResourceManager.GetString("UdpTraceListenerFooterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The footer of the message..
        /// </summary>
        internal static string UdpTraceListenerFooterPartName {
            get {
                return ResourceManager.GetString("UdpTraceListenerFooterPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formater for the message..
        /// </summary>
        internal static string UdpTraceListenerFormatDescription {
            get {
                return ResourceManager.GetString("UdpTraceListenerFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header of the message..
        /// </summary>
        internal static string UdpTraceListenerHeaderDescription {
            get {
                return ResourceManager.GetString("UdpTraceListenerHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header of the message..
        /// </summary>
        internal static string UdpTraceListenerHeaderPartName {
            get {
                return ResourceManager.GetString("UdpTraceListenerHeaderPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UdpTraceListener.
        /// </summary>
        internal static string UdpTraceListenerNode {
            get {
                return ResourceManager.GetString("UdpTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of remote hosts to send the message..
        /// </summary>
        internal static string UdpTraceListenerRemoteHostsDescription {
            get {
                return ResourceManager.GetString("UdpTraceListenerRemoteHostsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated list of remote hosts to send the message..
        /// </summary>
        internal static string UdpTraceListenerRemoteHostsPartName {
            get {
                return ResourceManager.GetString("UdpTraceListenerRemoteHostsPartName", resourceCulture);
            }
        }
    }
}
