//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scch.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scch.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add_64x64 {
            get {
                object obj = ResourceManager.GetObject("Add_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddAll_64x64 {
            get {
                object obj = ResourceManager.GetObject("AddAll_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddNew_64x64 {
            get {
                object obj = ResourceManager.GetObject("AddNew_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bullets_16x16 {
            get {
                object obj = ResourceManager.GetObject("Bullets_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar_64x64 {
            get {
                object obj = ResourceManager.GetObject("Calendar_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cancel_64x64 {
            get {
                object obj = ResourceManager.GetObject("Cancel_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle hinzufügen.
        /// </summary>
        public static string CommonCommands_AddAllDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_AddAllDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle hinzufügen.
        /// </summary>
        public static string CommonCommands_AddAllToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_AddAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string CommonCommands_AddDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_AddDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Eintrag.
        /// </summary>
        public static string CommonCommands_AddNewDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_AddNewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Eintrag hinzufügen.
        /// </summary>
        public static string CommonCommands_AddNewToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_AddNewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag hinzufügen.
        /// </summary>
        public static string CommonCommands_AddToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_AddToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzählungszeichen.
        /// </summary>
        public static string CommonCommands_BulletsDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_BulletsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzählungszeichen.
        /// </summary>
        public static string CommonCommands_BulletsToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_BulletsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string CommonCommands_CalendarDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_CalendarDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum bearbeiten.
        /// </summary>
        public static string CommonCommands_CalendarToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_CalendarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string CommonCommands_CancelDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_CancelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string CommonCommands_CancelToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_CancelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string CommonCommands_CopyDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_CopyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markierung in die Zwischenablage einfügen.
        /// </summary>
        public static string CommonCommands_CopyToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschneiden.
        /// </summary>
        public static string CommonCommands_CutDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_CutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markierung ausschneiden.
        /// </summary>
        public static string CommonCommands_CutToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_CutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalte löschen.
        /// </summary>
        public static string CommonCommands_DeleteColumnDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteColumnDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalte löschen.
        /// </summary>
        public static string CommonCommands_DeleteColumnToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteColumnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string CommonCommands_DeleteDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile löschen.
        /// </summary>
        public static string CommonCommands_DeleteRowDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteRowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile löschen.
        /// </summary>
        public static string CommonCommands_DeleteRowToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle löschen.
        /// </summary>
        public static string CommonCommands_DeleteTableDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteTableDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle löschen.
        /// </summary>
        public static string CommonCommands_DeleteTableToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteTableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag löschen.
        /// </summary>
        public static string CommonCommands_DeleteToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        public static string CommonCommands_DownloadDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_DownloadDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        public static string CommonCommands_DownloadToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_DownloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string CommonCommands_EditDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_EditDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag bearbeiten.
        /// </summary>
        public static string CommonCommands_EditToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string CommonCommands_FavoritesDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_FavoritesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string CommonCommands_FavoritesToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_FavoritesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finden.
        /// </summary>
        public static string CommonCommands_FindDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_FindDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finden.
        /// </summary>
        public static string CommonCommands_FindToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_FindToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erster Eintrag.
        /// </summary>
        public static string CommonCommands_FirstDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_FirstDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigiert zum ersten Eintrag.
        /// </summary>
        public static string CommonCommands_FirstToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_FirstToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        public static string CommonCommands_FolderDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_FolderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner anzeigen.
        /// </summary>
        public static string CommonCommands_FolderToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_FolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterleiten.
        /// </summary>
        public static string CommonCommands_ForwardMailDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_ForwardMailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht weiterleiten.
        /// </summary>
        public static string CommonCommands_ForwardMailToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_ForwardMailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string CommonCommands_HelpDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_HelpDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe anzeigen.
        /// </summary>
        public static string CommonCommands_HelpToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string CommonCommands_InformationDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_InformationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen anzeigen.
        /// </summary>
        public static string CommonCommands_InformationToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_InformationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalte links einfügen.
        /// </summary>
        public static string CommonCommands_InsertColumnLeftDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_InsertColumnLeftDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalte links einfügen.
        /// </summary>
        public static string CommonCommands_InsertColumnLeftToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_InsertColumnLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalte rechts einfügen.
        /// </summary>
        public static string CommonCommands_InsertColumnRightDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_InsertColumnRightDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalte rechts einfügen.
        /// </summary>
        public static string CommonCommands_InsertColumnRightToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_InsertColumnRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile oberhalb einfügen.
        /// </summary>
        public static string CommonCommands_InsertRowAboveDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_InsertRowAboveDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile oberhalb einfügen.
        /// </summary>
        public static string CommonCommands_InsertRowAboveToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_InsertRowAboveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile unterhalb einfügen.
        /// </summary>
        public static string CommonCommands_InsertRowBelowDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_InsertRowBelowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeile unterhalb einfügen.
        /// </summary>
        public static string CommonCommands_InsertRowBelowToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_InsertRowBelowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string CommonCommands_InternetDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_InternetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string CommonCommands_InternetToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_InternetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Eintrag.
        /// </summary>
        public static string CommonCommands_LastDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_LastDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigiert zum letzten Eintrag.
        /// </summary>
        public static string CommonCommands_LastToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_LastToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linie einfügen.
        /// </summary>
        public static string CommonCommands_LineDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_LineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linie einfügen.
        /// </summary>
        public static string CommonCommands_LineToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_LineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string CommonCommands_LoginDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_LoginDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am System anmelden.
        /// </summary>
        public static string CommonCommands_LoginToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_LoginToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string CommonCommands_LogoutDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_LogoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vom System abmelden.
        /// </summary>
        public static string CommonCommands_LogoutToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_LogoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende.
        /// </summary>
        public static string CommonCommands_MoveBottomDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_MoveBottomDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An das Ende verschieben.
        /// </summary>
        public static string CommonCommands_MoveBottomToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_MoveBottomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach unten.
        /// </summary>
        public static string CommonCommands_MoveDownDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_MoveDownDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach unten verschieben.
        /// </summary>
        public static string CommonCommands_MoveDownToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_MoveDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfang.
        /// </summary>
        public static string CommonCommands_MoveTopDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_MoveTopDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An den Anfang verschieben.
        /// </summary>
        public static string CommonCommands_MoveTopToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_MoveTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach oben.
        /// </summary>
        public static string CommonCommands_MoveUpDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_MoveUpDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach oben verschieben.
        /// </summary>
        public static string CommonCommands_MoveUpToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_MoveUpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string CommonCommands_NavigateBackDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_NavigateBackDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück navigieren.
        /// </summary>
        public static string CommonCommands_NavigateBackToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_NavigateBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorwärts.
        /// </summary>
        public static string CommonCommands_NavigateForwardDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_NavigateForwardDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorwärts navigieren.
        /// </summary>
        public static string CommonCommands_NavigateForwardToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_NavigateForwardToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string CommonCommands_NewDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_NewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string CommonCommands_NewMailDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_NewMailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Nachricht.
        /// </summary>
        public static string CommonCommands_NewMailToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_NewMailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Eintrag.
        /// </summary>
        public static string CommonCommands_NewToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächster Eintrag.
        /// </summary>
        public static string CommonCommands_NextDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_NextDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigiert zum nächsten Eintrag.
        /// </summary>
        public static string CommonCommands_NextToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_NextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummerierung.
        /// </summary>
        public static string CommonCommands_NumberingDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_NumberingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummerierung.
        /// </summary>
        public static string CommonCommands_NumberingToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_NumberingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CommonCommands_OkDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_OkDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CommonCommands_OkToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_OkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string CommonCommands_OpenDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_OpenDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string CommonCommands_OpenToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        public static string CommonCommands_PasteDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PasteDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus der Zwischenablage einfügen.
        /// </summary>
        public static string CommonCommands_PasteToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string CommonCommands_PauseDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PauseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe pausieren.
        /// </summary>
        public static string CommonCommands_PauseToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PauseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild einfügen.
        /// </summary>
        public static string CommonCommands_PictureDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PictureDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild einfügen.
        /// </summary>
        public static string CommonCommands_PictureToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PictureToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe.
        /// </summary>
        public static string CommonCommands_PlayDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PlayDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe starten.
        /// </summary>
        public static string CommonCommands_PlayToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PlayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau.
        /// </summary>
        public static string CommonCommands_PreviewDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PreviewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau anzeigen.
        /// </summary>
        public static string CommonCommands_PreviewToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PreviewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorheriger Eintrag.
        /// </summary>
        public static string CommonCommands_PreviousDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PreviousDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigiert zum vorherigen Eintrag.
        /// </summary>
        public static string CommonCommands_PreviousToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PreviousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        public static string CommonCommands_PrintDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PrintDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht drucken.
        /// </summary>
        public static string CommonCommands_PrintToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PrintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaften.
        /// </summary>
        public static string CommonCommands_PropertiesDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_PropertiesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaften anzeigen.
        /// </summary>
        public static string CommonCommands_PropertiesToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_PropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzeichnen.
        /// </summary>
        public static string CommonCommands_RecordDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_RecordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzeichnen start/stop.
        /// </summary>
        public static string CommonCommands_RecordToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_RecordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellen.
        /// </summary>
        public static string CommonCommands_RedoDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_RedoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderung wiederherstellen.
        /// </summary>
        public static string CommonCommands_RedoToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_RedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        public static string CommonCommands_RefreshDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_RefreshDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge aktualisieren.
        /// </summary>
        public static string CommonCommands_RefreshToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle entfernen.
        /// </summary>
        public static string CommonCommands_RemoveAllDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_RemoveAllDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle entfernen.
        /// </summary>
        public static string CommonCommands_RemoveAllToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_RemoveAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        public static string CommonCommands_RemoveDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_RemoveDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag entfernen.
        /// </summary>
        public static string CommonCommands_RemoveToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_RemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbenennen.
        /// </summary>
        public static string CommonCommands_RenameDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_RenameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag umbenennen.
        /// </summary>
        public static string CommonCommands_RenameToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_RenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string CommonCommands_SaveDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_SaveDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag speichern.
        /// </summary>
        public static string CommonCommands_SaveToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirmfoto.
        /// </summary>
        public static string CommonCommands_ScreenshotDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_ScreenshotDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirmfoto erstellen.
        /// </summary>
        public static string CommonCommands_ScreenshotToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_ScreenshotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string CommonCommands_SearchDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_SearchDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string CommonCommands_SearchToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden.
        /// </summary>
        public static string CommonCommands_SendMailDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_SendMailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht senden.
        /// </summary>
        public static string CommonCommands_SendMailToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_SendMailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string CommonCommands_SettingsDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_SettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen anzeigen.
        /// </summary>
        public static string CommonCommands_SettingsToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        public static string CommonCommands_StartDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_StartDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        public static string CommonCommands_StartToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_StartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string CommonCommands_StopDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_StopDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string CommonCommands_StopToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_StopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisieren.
        /// </summary>
        public static string CommonCommands_SynchronizeDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_SynchronizeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisieren.
        /// </summary>
        public static string CommonCommands_SynchronizeToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_SynchronizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle einfügen.
        /// </summary>
        public static string CommonCommands_TableDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_TableDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle einfügen.
        /// </summary>
        public static string CommonCommands_TableToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_TableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig.
        /// </summary>
        public static string CommonCommands_UndoDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_UndoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderung rückgängig machen.
        /// </summary>
        public static string CommonCommands_UndoToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_UndoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heraufladen.
        /// </summary>
        public static string CommonCommands_UploadDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_UploadDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heraufladen.
        /// </summary>
        public static string CommonCommands_UploadToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_UploadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergrößern.
        /// </summary>
        public static string CommonCommands_ZoomInDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_ZoomInDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeige vergrößern.
        /// </summary>
        public static string CommonCommands_ZoomInToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_ZoomInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkleinern.
        /// </summary>
        public static string CommonCommands_ZoomOutDisplayName {
            get {
                return ResourceManager.GetString("CommonCommands_ZoomOutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeige verkleinern.
        /// </summary>
        public static string CommonCommands_ZoomOutToolTip {
            get {
                return ResourceManager.GetString("CommonCommands_ZoomOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy_64x64 {
            get {
                object obj = ResourceManager.GetObject("Copy_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cut_64x64 {
            get {
                object obj = ResourceManager.GetObject("Cut_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete_64x64 {
            get {
                object obj = ResourceManager.GetObject("Delete_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeleteColumn_16x16 {
            get {
                object obj = ResourceManager.GetObject("DeleteColumn_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeleteRow_16x16 {
            get {
                object obj = ResourceManager.GetObject("DeleteRow_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeleteTable_16x16 {
            get {
                object obj = ResourceManager.GetObject("DeleteTable_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Download_64x64 {
            get {
                object obj = ResourceManager.GetObject("Download_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit_64x64 {
            get {
                object obj = ResourceManager.GetObject("Edit_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Favorites_64x64 {
            get {
                object obj = ResourceManager.GetObject("Favorites_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Find_64x64 {
            get {
                object obj = ResourceManager.GetObject("Find_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap First_64x64 {
            get {
                object obj = ResourceManager.GetObject("First_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folder_64x64 {
            get {
                object obj = ResourceManager.GetObject("Folder_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ForwardMail_64x64 {
            get {
                object obj = ResourceManager.GetObject("ForwardMail_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Help_64x64 {
            get {
                object obj = ResourceManager.GetObject("Help_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Information_64x64 {
            get {
                object obj = ResourceManager.GetObject("Information_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InsertColumnLeft_16x16 {
            get {
                object obj = ResourceManager.GetObject("InsertColumnLeft_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InsertColumnRight_16x16 {
            get {
                object obj = ResourceManager.GetObject("InsertColumnRight_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InsertRowAbove_16x16 {
            get {
                object obj = ResourceManager.GetObject("InsertRowAbove_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InsertRowBelow_16x16 {
            get {
                object obj = ResourceManager.GetObject("InsertRowBelow_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Internet_64x64 {
            get {
                object obj = ResourceManager.GetObject("Internet_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Last_64x64 {
            get {
                object obj = ResourceManager.GetObject("Last_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Line_32x32 {
            get {
                object obj = ResourceManager.GetObject("Line_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Login_64x64 {
            get {
                object obj = ResourceManager.GetObject("Login_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logout_64x64 {
            get {
                object obj = ResourceManager.GetObject("Logout_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MoveBottom_64x64 {
            get {
                object obj = ResourceManager.GetObject("MoveBottom_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MoveDown_64x64 {
            get {
                object obj = ResourceManager.GetObject("MoveDown_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MoveTop_64x64 {
            get {
                object obj = ResourceManager.GetObject("MoveTop_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MoveUp_64x64 {
            get {
                object obj = ResourceManager.GetObject("MoveUp_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NavigateBack_64x64 {
            get {
                object obj = ResourceManager.GetObject("NavigateBack_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NavigateForward_64x64 {
            get {
                object obj = ResourceManager.GetObject("NavigateForward_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap New_64x64 {
            get {
                object obj = ResourceManager.GetObject("New_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NewMail_64x64 {
            get {
                object obj = ResourceManager.GetObject("NewMail_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Next_64x64 {
            get {
                object obj = ResourceManager.GetObject("Next_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Numbering_16x16 {
            get {
                object obj = ResourceManager.GetObject("Numbering_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ok_64x64 {
            get {
                object obj = ResourceManager.GetObject("Ok_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Open_64x64 {
            get {
                object obj = ResourceManager.GetObject("Open_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Paste_64x64 {
            get {
                object obj = ResourceManager.GetObject("Paste_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pause_64x64 {
            get {
                object obj = ResourceManager.GetObject("Pause_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Picture_64x64 {
            get {
                object obj = ResourceManager.GetObject("Picture_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Play_64x64 {
            get {
                object obj = ResourceManager.GetObject("Play_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview_64x64 {
            get {
                object obj = ResourceManager.GetObject("Preview_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Previous_64x64 {
            get {
                object obj = ResourceManager.GetObject("Previous_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print_64x64 {
            get {
                object obj = ResourceManager.GetObject("Print_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Properties_64x64 {
            get {
                object obj = ResourceManager.GetObject("Properties_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Record_64x64 {
            get {
                object obj = ResourceManager.GetObject("Record_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Redo_64x64 {
            get {
                object obj = ResourceManager.GetObject("Redo_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_64x64 {
            get {
                object obj = ResourceManager.GetObject("Refresh_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remove_64x64 {
            get {
                object obj = ResourceManager.GetObject("Remove_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveAll_64x64 {
            get {
                object obj = ResourceManager.GetObject("RemoveAll_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rename_64x64 {
            get {
                object obj = ResourceManager.GetObject("Rename_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save_64x64 {
            get {
                object obj = ResourceManager.GetObject("Save_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_64x64 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search_64x64 {
            get {
                object obj = ResourceManager.GetObject("Search_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SendMail_64x64 {
            get {
                object obj = ResourceManager.GetObject("SendMail_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings_64x64 {
            get {
                object obj = ResourceManager.GetObject("Settings_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Start_64x64 {
            get {
                object obj = ResourceManager.GetObject("Start_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stop_64x64 {
            get {
                object obj = ResourceManager.GetObject("Stop_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Synchronize_64x64 {
            get {
                object obj = ResourceManager.GetObject("Synchronize_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Table_32x32 {
            get {
                object obj = ResourceManager.GetObject("Table_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelleneigenschaften bearbeiten.
        /// </summary>
        public static string TablePropertiesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch.
        /// </summary>
        public static string TablePropertiesViewModelAutoWidthDisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelAutoWidthDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmenfarbe.
        /// </summary>
        public static string TablePropertiesViewModelBorderBrushDisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelBorderBrushDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmenbreite.
        /// </summary>
        public static string TablePropertiesViewModelBorderThicknessDisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelBorderThicknessDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Spalten.
        /// </summary>
        public static string TablePropertiesViewModelColumnCountDisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelColumnCountDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        public static string TablePropertiesViewModelColumnCountRange {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelColumnCountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaltenbreite.
        /// </summary>
        public static string TablePropertiesViewModelColumnWidthDisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelColumnWidthDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        public static string TablePropertiesViewModelColumnWidthRange {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelColumnWidthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Zeilen.
        /// </summary>
        public static string TablePropertiesViewModelRowCountDisplayName {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelRowCountDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        public static string TablePropertiesViewModelRowCountRange {
            get {
                return ResourceManager.GetString("TablePropertiesViewModelRowCountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo_64x64 {
            get {
                object obj = ResourceManager.GetObject("Undo_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Upload_64x64 {
            get {
                object obj = ResourceManager.GetObject("Upload_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZoomIn_64x64 {
            get {
                object obj = ResourceManager.GetObject("ZoomIn_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZoomOut_64x64 {
            get {
                object obj = ResourceManager.GetObject("ZoomOut_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
