//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scch.DomainModel.EntityFramework.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scch.DomainModel.EntityFramework.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anweisungstyp.
        /// </summary>
        internal static string Anweisungstyp_DisplayName {
            get {
                return ResourceManager.GetString("Anweisungstyp_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellcode.
        /// </summary>
        internal static string Auspraegung_Bestellcode_DisplayName {
            get {
                return ResourceManager.GetString("Auspraegung_Bestellcode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; darf maximal {1} Zeichen lang sein..
        /// </summary>
        internal static string Auspraegung_Bestellcode_Length {
            get {
                return ResourceManager.GetString("Auspraegung_Bestellcode_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist erforderlich..
        /// </summary>
        internal static string Auspraegung_Bestellcode_Required {
            get {
                return ResourceManager.GetString("Auspraegung_Bestellcode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        internal static string Auspraegung_Bild_DisplayName {
            get {
                return ResourceManager.GetString("Auspraegung_Bild_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausprägung.
        /// </summary>
        internal static string Auspraegung_DisplayName {
            get {
                return ResourceManager.GetString("Auspraegung_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        internal static string Auspraegung_Laenge_Range {
            get {
                return ResourceManager.GetString("Auspraegung_Laenge_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist erforderlich..
        /// </summary>
        internal static string Auspraegung_Laenge_Required {
            get {
                return ResourceManager.GetString("Auspraegung_Laenge_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktmerkmal.
        /// </summary>
        internal static string Auspraegung_Produktmerkmal_DisplayName {
            get {
                return ResourceManager.GetString("Auspraegung_Produktmerkmal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        internal static string Auspraegung_Reihenfolge_Range {
            get {
                return ResourceManager.GetString("Auspraegung_Reihenfolge_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist erforderlich..
        /// </summary>
        internal static string Auspraegung_Reihenfolge_Required {
            get {
                return ResourceManager.GetString("Auspraegung_Reihenfolge_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        internal static string EntityWithBezeichnung_Bezeichnung_DisplayName {
            get {
                return ResourceManager.GetString("EntityWithBezeichnung_Bezeichnung_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; darf maximal {1} Zeichen lang sein..
        /// </summary>
        internal static string EntityWithBezeichnung_Bezeichnung_Length {
            get {
                return ResourceManager.GetString("EntityWithBezeichnung_Bezeichnung_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist erforderlich..
        /// </summary>
        internal static string EntityWithBezeichnung_Bezeichnung_Required {
            get {
                return ResourceManager.GetString("EntityWithBezeichnung_Bezeichnung_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkmalsgruppe.
        /// </summary>
        internal static string Merkmalsgruppe_DisplayName {
            get {
                return ResourceManager.GetString("Merkmalsgruppe_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string Produkt_DisplayName {
            get {
                return ResourceManager.GetString("Produkt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grundpreis.
        /// </summary>
        internal static string Produkt_Grundpreis_DisplayName {
            get {
                return ResourceManager.GetString("Produkt_Grundpreis_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        internal static string Produkt_Grundpreis_Range {
            get {
                return ResourceManager.GetString("Produkt_Grundpreis_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer.
        /// </summary>
        internal static string Produkt_Nummer_DisplayName {
            get {
                return ResourceManager.GetString("Produkt_Nummer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; darf maximal {1} Zeichen lang sein..
        /// </summary>
        internal static string Produkt_Nummer_Length {
            get {
                return ResourceManager.GetString("Produkt_Nummer_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist erforderlich..
        /// </summary>
        internal static string Produkt_Nummer_Required {
            get {
                return ResourceManager.GetString("Produkt_Nummer_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktgruppe.
        /// </summary>
        internal static string Produkt_Produktgruppe_DisplayName {
            get {
                return ResourceManager.GetString("Produkt_Produktgruppe_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktversionen.
        /// </summary>
        internal static string Produkt_Produktversionen_DisplayName {
            get {
                return ResourceManager.GetString("Produkt_Produktversionen_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktgruppe.
        /// </summary>
        internal static string Produktgruppe_DisplayName {
            get {
                return ResourceManager.GetString("Produktgruppe_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausprägungen.
        /// </summary>
        internal static string Produktmerkmal_Auspraegungen_DisplayName {
            get {
                return ResourceManager.GetString("Produktmerkmal_Auspraegungen_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktmerkmal.
        /// </summary>
        internal static string Produktmerkmal_DisplayName {
            get {
                return ResourceManager.GetString("Produktmerkmal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge.
        /// </summary>
        internal static string Produktmerkmal_Laenge_DisplayName {
            get {
                return ResourceManager.GetString("Produktmerkmal_Laenge_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        internal static string Produktmerkmal_Laenge_Range {
            get {
                return ResourceManager.GetString("Produktmerkmal_Laenge_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkmalsgruppe.
        /// </summary>
        internal static string Produktmerkmal_Merkmalsgruppe_DisplayName {
            get {
                return ResourceManager.GetString("Produktmerkmal_Merkmalsgruppe_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausprägungen.
        /// </summary>
        internal static string Produktversion_Auspraegungen_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_Auspraegungen_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktversion.
        /// </summary>
        internal static string Produktversion_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        internal static string Produktversion_Kommentar_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_Kommentar_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist erforderlich..
        /// </summary>
        internal static string Produktversion_Kommentar_Required {
            get {
                return ResourceManager.GetString("Produktversion_Kommentar_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer.
        /// </summary>
        internal static string Produktversion_Nummer_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_Nummer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; muss größer oder gleich {1} sein..
        /// </summary>
        internal static string Produktversion_Nummer_Range {
            get {
                return ResourceManager.GetString("Produktversion_Nummer_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string Produktversion_Produkt_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_Produkt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusverlauf.
        /// </summary>
        internal static string Produktversion_Statusverlauf_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_Statusverlauf_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuordnungen.
        /// </summary>
        internal static string Produktversion_Zuordnungen_DisplayName {
            get {
                return ResourceManager.GetString("Produktversion_Zuordnungen_DisplayName", resourceCulture);
            }
        }
    }
}
